### ISSUE TITLE
Yubikey class names not correct?

### ISSUE THREAD

**Issue by gregharvey** [simplesamlphp/simplesamlphp-module-yubikey#3]
Hi Jaime,

I got this working in the older version of simpleSAMLphp (the one that ships with Debian Jessie, v1.13.1, by applying the changes you can see in this branch of my fork of your repo:

https://github.com/codeenigma/simplesamlphp-module-yubikey/commit/14b55269d789dc9208d2b0daee4ba7257d5bff74

I assumed the errors I was getting with regard to class names were due to out of date class loading in this older version, things like this:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
0 /var/www/simplesamlphp/www/module.php:180 (N/A)
Caused by: Exception: Could not resolve 'yubikey:OTP': No class named 'sspmod_yubikey_Auth_Process_OTP'.
Backtrace:
11 /var/www/simplesamlphp/lib/SimpleSAML/Module.php:152 (SimpleSAML_Module::resolveClass)
10 /var/www/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php:151 (SimpleSAML_Auth_ProcessingChain::parseFilter)
9 /var/www/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php:130 (SimpleSAML_Auth_ProcessingChain::parseFilterList)
8 /var/www/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php:58 (SimpleSAML_Auth_ProcessingChain::__construct)
7 /var/www/simplesamlphp/lib/SimpleSAML/IdP.php:325 (SimpleSAML_IdP::postAuth)
6 [builtin] (call_user_func)
5 /var/www/simplesamlphp/lib/SimpleSAML/Auth/Source.php:229 (SimpleSAML_Auth_Source::loginCompleted)
4 [builtin] (call_user_func)
3 /var/www/simplesamlphp/lib/SimpleSAML/Auth/Source.php:145 (SimpleSAML_Auth_Source::completeAuth)
2 /var/www/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:266 (sspmod_core_Auth_UserPassBase::handleLogin)
1 /var/www/simplesamlphp/modules/core/www/loginuserpass.php:67 (require)
0 /var/www/simplesamlphp/www/module.php:137 (N/A)
```

However, I've checked out and built the latest tag from the simpleSAMLphp repo, v1.14.14, and I'm getting this same error. So I think this might actually be a bug and the class name needs fixing? Happy to make a PR if you agree this is something that needs fixing. Or if I'm doing something wrong, let me know, either way! :-)

Thanks,

Greg

**Comment by jaimeperez** [comment]
Hi @gregharvey!

How did you install the module? I haven't tested in a while, but it was working for me.

**Comment by gregharvey** [comment]
Hey, I just installed it with Composer as per the readme. Everything *seems* to be in the right place. Same goes for simpleSAMLphp itself, I pulled the repo, checked out the v1.14.14 tag and did a `composer install`. It all *looks* fine, but I keep getting this problem...

**Comment by jaimeperez** [comment]
Now that I look into it, I think it requires master, as the module is using namespaces. Can you try to pull master instead of 1.14.14, run composer again, and test it?

**Comment by gregharvey** [comment]
Yes, works with 'master'! I'm happy to use 'master' assuming the next major release will use namespaces too? :-)

By the way, just fyi, the version of this registered with Composer is not up to date, I had to re-apply https://github.com/simplesamlphp/simplesamlphp-module-yubikey/commit/fa485d25eb9f08422d5cbd5d5a359f5bdb640530

**Comment by jaimeperez** [comment]
Yep, 1.15 will be already using namespaces, and the plan is to have everything migrated for 2.0. Usually master is relatively stable, but you should probably stick to a specific commit that you have verified works fine for you.

Regarding the bugfix you are mentioning, that's my fault. I had a 0.1.1. tag locally, but never pushed it upstream. Should be solved now 😉

**Comment by gregharvey** [comment]
Excellent, thanks!
